backend:
  name: github
  repo: josue-veloso/joao-barbalho
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "config"
    label: "Configurações"
    files:
      - label: "Página Sobre"
        name: "about"
        file: "content/about.json"
        fields:
          - {label: "Título (PT)", name: "title_pt", widget: "string", default: "SOBRE"}
          - {label: "Texto (PT)", name: "text_pt", widget: "text"}
          - {label: "Título (EN)", name: "title_en", widget: "string", default: "ABOUT"}
          - {label: "Texto (EN)", name: "text_en", widget: "text"}
          - {label: "Título (ES)", name: "title_es", widget: "string", default: "ACERCA DE"}
          - {label: "Texto (ES)", name: "text_es", widget: "text"}
